# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class  < Formula
    desc "brew formula"
    homepage "https://github.com/rvigo/asdasdsa"
    version "v1.0.6"
    license "MIT"
    url "https://github.com/rvigo/asdasdsa/releases/download/v1.0.6/asdasdsa_v1.0.6.tar.gz"
    hash "e3ab0ecaa6d0b5a86ef7b80e8f61435f741cba257e0d6acf4b71e3a2a23665c1"

    def install
        "bin.install &quot;asdasdsa&quot;"
    end

    test do
        asdasdsa --version
    end
end
