# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Asdasdsa < Formula
  desc "Brew formula"
  homepage "https://github.com/rvigo/asdasdsa"
  url "https://github.com/rvigo/asdasdsa/archive/refs/tags/v1.2.1.tar.gz"
  sha256 "d30ed609fd3062cc9528550117e599500a6b2bfbbe5ab392ee75f1bc775593e8"
  license "MIT"
  head "https://github.com/rvigo/asdasdsa.git", branch: "main"

  def install
    system "cargo", "install", *std_cargo_args
  end
end
