# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Asdasdsa < Formula
  desc "Brew formula"
  homepage "https://github.com/rvigo/asdasdsa"
  license "MIT"
  url "https://github.com/rvigo/asdasdsa/releases/download/v1.2.0/asdasdsa-v1.2.0-x86_64-linux.tar.gz"
  version "1.2.0"
  sha256 "935770ec1406178c5f15feae706d98451cbf2e01a1ae8bd6a5251ebbd5487ab9"
  head "https://github.com/rvigo/asdasdsa.git", branch: "main"

  def install
    system "cargo", "install", *std_cargo_args
  end
end
