# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Hello < Formula
    desc "B"
    homepage "https://example.com"
    version "v9.9.9"
    license "MIT"
    url "https://github.com/rvigo/asdasdsa/releases/download/v9.9.9/rustreleaser_v9.9.9.tar.gz"
    hash "ee8484a54763ca970625d7d8394143a606a905e8de5d022ffc56c4b33cca3b48"

    def install
       bin.install "hello"
    end

    def caveats
        "This is a test formula"
    end

    test do
        echo "Hello, World!"
    end
end
