# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Hello < Formula
    desc "B"
    homepage "https://example.com"
    version "v9.9.9"
    license "MIT"
    url "https://github.com/rvigo/asdasdsa/releases/download/v9.9.9/rustreleaser_v9.9.9.tar.gz"
    hash "65a43a3f6ea0302bd68b728276ef3eb1d6e3a048449af9423aa29846d46fddbc"

    def install
       bin.install "hello"
    end

    def caveats
        "This is a test formula"
    end

    test do
        echo "Hello, World!"
    end
end
