# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Hello < Formula
    desc "B"
    homepage "https://example.com"
    version "v9.9.9"
    license "MIT"
    url "https://github.com/rvigo/asdasdsa/releases/download/v9.9.9/rustreleaser_v9.9.9.tar.gz"
    hash "ef6dd9a0033f657371e4326b80cd2e5114d3b790bee76221c4bd715714340795"

    def install
       bin.install "hello"
    end

    def caveats
        "This is a test formula"
    end

    test do
        echo "Hello, World!"
    end
end
