# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class  < Formula
    desc "B"
    homepage "https://example.com"
    version "v9.9.9"
    license "MIT"
    url "https://github.com/rvigo/asdasdsa/releases/download/v9.9.9/rustreleaser_v9.9.9_x86_64_unknown-linux-gnu.tar.gz"
    hash "54f8fe57a7f1df4705c9e11af66a8a35e6695519d6bfe19610c8e86bec9d35ae"

    def install
        "This is a test formula"
    end

    def caveats
        "This is a test formula"
    end

    test do
        echo &quot;Hello, World!&quot;
    end
end
