# typed: false
# frozen_string_literal: true

# DO NOT EDIT THIS FILE

class Test < Formula
    desc "brew formula"
    homepage "https://github.com/rvigo/asdasdsa"
    license "MIT"
    version "v1.2.0"
    head "https://github.com/rvigo/asdasdsa.git", branch: "main"

    depends_on "rust" => :build
    
    def install
        system "cargo", "--config", "'bin.name = asdasdsa-beta'", "install", *std_cargo_args
    end
end
